### ISSUE TITLE
error: (void-function lsp-scala-enable)

### ISSUE THREAD

**Issue by strobe** [rossabaker/lsp-scala#11]
The Readme has a call of `lsp-scala-enable` as part of configuration process but `lsp-scala.el` doesn't have it. Also, it looks like `lsp-mode` also doesn't have this function definition.
Where `lsp-scala-enable` should come from? Is it replaced with something new?

**Comment by strobe** [comment]
seems like I got this error because tried to use the latest version of `lsp-mode` and `lsp-ui`, with a version from melpa stable this error doesn't happen

**Comment by ascander** [comment]
Same error, and workaround, here.

**Comment by rossabaker** [comment]
There is an [open PR](https://github.com/rossabaker/lsp-scala/pull/9) for moving to "lsp next".  I wonder whether it makes sense to focus on that.

**Comment by rossabaker** [comment]
This is fixed by #14, and properly documented in the meantime by https://github.com/scalameta/metals/pull/419.
