### ISSUE TITLE
one chance to start the server...

### ISSUE THREAD

**Issue by fommil** [rossabaker/lsp-scala#4]
If the server fails to come up, any subsequent `lsp-scala-enable` calls are apparently ignored.

I can't figure out how to reset the state, other than restart emacs, which is always tragic.

**Comment by rossabaker** [comment]
I've noticed this, too.  `lsp-restart-workspace` doesn't work.  I see there is an `lsp--uninitialize-workspace`, which looks promising, but also looks like it should already be called.  I haven't yet tracked down whether I'm missing a hook or if lsp-mode should manage this for us.
