### ISSUE TITLE
customize lsp-response-timeout

### ISSUE THREAD

**Issue by hb9** [rossabaker/lsp-scala#7]
Due to long startup-times of metals for larger projects the default value of [lsp-response-timeout](https://github.com/emacs-lsp/lsp-mode/blob/3677a92e29a2a76ff6120647dfa3fef9b7fa63a9/lsp-io.el#L26) of 10 seconds is not enough. It took me some time to figure that out. Maybe you could mention the necessity of increasing that value in the readme?

If the `lsp-response-timeout` value is to small the time-out-error is interrupting the initialization which is causing that `lsp--workspace-server-capabilities` is not setup correctly.

**Comment by statictypeddog** [comment]
Did you find a workaround ?

**Comment by rossabaker** [comment]
Changes were made to metals to do more work after the initialization.  I think this is no longer an issue.  If I'm wrong, please reopen.

**Comment by olafurpg** [comment]
The `initialize` request should not take more than a few hundred milliseconds at most. The indexing work happens now after the `initialized` notification.
